import {SOURCES,escapeHTML as esc,concepts,validateSpec,retrieve,importResponse,digest,verifySnapshot} from './core.mjs';
import {LocalStore} from './storage.mjs';
import {newJob,runJob} from './runner.mjs?v=complete-fix-2';
import * as model from './model.mjs?v=complete-fix-2';
import {errorMessage} from './errors.mjs';
import {localJSON} from './assets.mjs';
const $=id=>document.getElementById(id),json=value=>'<pre>'+esc(JSON.stringify(value,null,2))+'</pre>';
const badge=p=>'<span class="badge '+(['FACT','DERIVED','ASSUMPTION','SIMULATED'].includes(p)?p:'SIMULATED')+'">'+esc(p)+'</span>';
let store,aliases={},snapshot,current,tab='overview',busy=false,loadingModel=false,controller,viewer,worldMode='reality',epoch=0;
const status=(message,error=false)=>{$('status').textContent=message;$('status').className=error?'error':'';};
function buttons(){$('cancel-load').hidden=!loadingModel;document.querySelectorAll('#scenario-form input,#scenario-form textarea,#scenario-form select,#import-file,#import-source,#import-query').forEach(x=>x.disabled=busy);const loaded=model.ready();$('run').disabled=busy||!store||!loaded||!snapshot?.snapshot.records.length||!$('reviewed').checked||!$('public-only').checked;$('retrieve').disabled=busy||!store;$('load-model').disabled=busy||loaded;$('unload-model').disabled=busy||!loaded;$('clear-data').disabled=busy;$('new-scenario').disabled=busy;$('import-evidence').disabled=busy||!store;}
async function list(){const jobs=await store.list();$('scenario-list').innerHTML=jobs.length?jobs.map(j=>'<button class="scenario-button" data-scenario="'+esc(j.id)+'">'+esc(j.spec.title)+'<span>'+esc(j.state)+' · '+j.next_step+' saved steps</span></button>').join(''):'<p class="muted">No local scenarios yet.</p>';}
function link(url,label){try{const u=new URL(url);if(u.protocol!=='https:')return esc(label);return '<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+'</a>';}catch{return esc(label);}}
function destroyGlobe(){if(viewer){viewer.destroy();viewer=undefined;}}
function render(){
  const generation=++epoch;destroyGlobe();$('overview').hidden=tab!=='overview';$('detail').hidden=tab==='overview';
  document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  $('snapshot-summary').textContent=snapshot?snapshot.snapshot.records.length+' record occurrences · SHA-256 '+snapshot.sha256:'No evidence snapshot selected.';
  if(tab==='overview'){buttons();return;}
  const empty=t=>'<div class="empty">'+esc(t)+'</div>';let html='';
  if(tab==='evidence'){
    html='<h2>Frozen public evidence</h2><p class="muted">FACT preserves provider fields without independently confirming their truth. Imported source attribution remains ASSUMPTION.</p>';
    if(!snapshot)html+=empty('Retrieve or import public-source evidence first.');
    else{const s=snapshot.snapshot;html+='<p class="muted">Snapshot '+esc(snapshot.id)+' · '+esc(new Date(s.created_at).toLocaleString())+'</p><h3>Resolution hints</h3>'+s.entities.map(e=>'<div class="record">'+badge('DERIVED')+esc(e.input)+' → '+esc(e.normalized)+'<p>'+esc(e.method)+'</p></div>').join('');html+='<h3>Source coverage</h3>'+s.receipts.map(r=>'<div class="record"><strong>'+esc(SOURCES[r.source])+'</strong> / '+esc(r.query)+' · '+esc(r.status)+(r.error?'<p>'+esc(r.error)+'</p>':'')+'<details><summary>Receipt and raw response</summary>'+json(r)+'</details></div>').join('');html+='<h3>Source records</h3>'+s.records.map(r=>'<article class="record">'+badge(r.provenance)+link(r.url,r.title)+'<p>'+esc(r.source_id)+' · '+esc(r.meaning)+'</p><p class="muted">Receipt '+esc(r.receipt_id)+' · field '+esc(r.locator)+'</p><details><summary>Inspect preserved record</summary>'+json(r.raw)+'</details></article>').join('');html+='<details><summary>Evidence graph and integrity</summary>'+json({sha256:snapshot.sha256,graph:s.graph,limitations:s.limitations})+'</details>';}
  }
  if(tab==='agents'){html='<h2>Synthetic stakeholder inspection</h2><p class="muted">Hypothetical roles are SIMULATED. Generated statements do not represent real people or advice.</p>';html+=current?current.agents.map((a,i)=>'<article class="record">'+badge('SIMULATED')+' <button data-agent="'+i+'">'+esc(a.name)+'</button><p>'+esc(a.focus)+'</p></article>').join(''):empty('Run or select a scenario to inspect agents.');}
  if(tab==='simulation'){
    html='<h2>Browser simulation progress</h2>';
    if(!current)html+=empty('Create or select a scenario.');else{html+='<p><strong>'+esc(current.spec.title)+'</strong> · '+esc(current.state)+'</p><progress value="'+current.progress+'" max="100" aria-label="Saved simulation progress"></progress><p class="muted">'+current.next_step+' / '+(current.spec.rounds*current.agents.length)+' saved interactions. Keep this tab open. Progress counts saved steps, not scientific confidence.</p>'+(current.error?'<p class="error">'+esc(current.error)+'</p>':'')+'<div class="actions">'+(busy&&current.state==='running'?'<button id="pause-run">Pause run</button>':'')+(!busy&&['paused','failed','interrupted','ready'].includes(current.state)?'<button id="resume-run" '+(!model.ready()?'disabled':'')+'>Resume saved run</button>':'')+'<button id="export-run">Export JSON</button></div><p class="muted">The local model sees up to eight record titles/identifiers and bounded recent statements. Full provider payloads remain available in Evidence and export.</p>';html+=current.events.map(e=>'<article class="record">'+badge('SIMULATED')+'<strong>'+esc(e.agent_id)+' · round '+e.round+'</strong><p>'+esc(e.statement)+'</p><p class="muted">Needs verification: '+esc(e.uncertainty)+'</p><p class="muted">Model-selected references: '+esc(e.references.map(r=>r.ref).join(', ')||'none')+'</p></article>').join('');}
  }
  if(tab==='world'){
    html='<h2>Evidence geography</h2><div class="mode-buttons">'+['reality','simulation','difference'].map(m=>'<button data-world="'+m+'" aria-pressed="'+(m===worldMode)+'">'+m[0].toUpperCase()+m.slice(1)+'</button>').join('')+'</div>';
    if(worldMode!=='reality')html+=empty('This browser model does not produce validated geographic changes. No simulation or difference layer is inferred from narrative text.');
    else{
      const locations=(snapshot?.snapshot.locations||[]).filter(p=>p.provenance==='FACT');
      html+='<p class="muted">Only coordinates returned directly by ClinicalTrials.gov appear as markers. The bundled world imagery is reference context. Unverified imported coordinates are excluded.</p><div id="globe" aria-label="Evidence globe and source-reported trial locations"></div>';
      html+=locations.length?'<div class="table-wrap"><table><thead><tr><th>Source facility</th><th>Latitude</th><th>Longitude</th></tr></thead><tbody>'+locations.map(p=>'<tr><td>'+esc(p.label)+'</td><td>'+p.lat+'</td><td>'+p.lon+'</td></tr>').join('')+'</tbody></table></div>':empty('No source-reported trial coordinates are available in this snapshot. Select ClinicalTrials.gov when retrieving evidence. Literature, gene and drug records are not assigned invented map locations.');
      queueMicrotask(()=>globe(locations,generation));
    }
  }
  if(tab==='report'){html='<h2>Labeled research report</h2>';if(!current?.report)html+=empty('A report is available after all saved interactions complete.');else{const r=current.report;html+='<p>'+badge('DERIVED')+' '+esc(r.method)+'</p><h3>'+esc(r.title)+'</h3><p class="muted">Evidence SHA-256 '+esc(r.evidence_sha256)+'</p><h3>Explicit assumptions</h3>'+r.assumptions.map(a=>'<p>'+badge('ASSUMPTION')+' '+esc(a.text)+'</p>').join('')+'<h3>Generated stakeholder responses</h3>'+r.statements.map(s=>'<article class="record">'+badge('SIMULATED')+' '+esc(s.agent_id)+' · round '+s.round+'<p>'+esc(s.statement)+'</p><p class="muted">Uncertainty: '+esc(s.uncertainty)+'</p><p class="muted">Model-selected references, not verification: '+esc(s.references.map(x=>x.ref).join(', ')||'none')+'</p></article>').join('')+'<h3>Limitations</h3>'+r.limitations.map(l=>'<p class="muted">'+esc(l)+'</p>').join('')+'<div class="actions"><button id="export-run">Export JSON</button><button id="export-report">Download report text</button></div>';}}
  $('detail').innerHTML=html;buttons();
}
async function globe(locations,generation){
  try{
    globalThis.CESIUM_BASE_URL='/assets/globe/';
    const C=await import('/assets/globe/index.js');
    const imagery=await C.TileMapServiceImageryProvider.fromUrl('/assets/globe/Assets/Textures/NaturalEarthII/',{maximumLevel:2,credit:'Natural Earth II — bundled reference imagery'});
    if(generation!==epoch||!$('globe'))return;
    viewer=new C.Viewer('globe',{baseLayer:new C.ImageryLayer(imagery),terrainProvider:new C.EllipsoidTerrainProvider(),animation:false,timeline:false,geocoder:false,baseLayerPicker:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,selectionIndicator:false,infoBox:false});
    for(const p of locations)viewer.entities.add({position:C.Cartesian3.fromDegrees(p.lon,p.lat),point:{pixelSize:8,color:C.Color.fromCssColorString('#14B8A6')},name:String(p.label)});
    viewer.scene.globe.baseColor=C.Color.fromCssColorString('#123659');
    if(locations.length)await viewer.zoomTo(viewer.entities);
  }catch(e){if(generation===epoch&&$('globe'))$('globe').textContent='Globe unavailable: '+errorMessage(e)+'. Source coordinates remain in the table.';}
}
function download(value,name,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportRun(){const job=structuredClone(current),evidence=structuredClone(snapshot);await verifySnapshot(evidence);download(JSON.stringify({schema:'oncotics-browser-export/1',scenario:job,evidence,integrity:{scenario_sha256:await digest(job),evidence_sha256:evidence.sha256}},null,2),'oncotics-scenario-'+job.id+'.json');}
async function select(id){if(busy)throw Error('Pause the current operation before selecting another scenario.');const job=await store.get(id);if(!job)throw Error('Local scenario not found.');const evidence=await store.snapshot(job.snapshot_id);if(!evidence)throw Error('This scenario is missing its evidence snapshot.');await verifySnapshot(evidence);current=job;snapshot=evidence;tab='simulation';render();}
async function execute(){if(!navigator.locks)throw Error('This browser cannot coordinate safe local runs. Use a current WebGPU-compatible browser.');const loaded=model.identity();if(current.model.id!==loaded.id||current.model.revision!==loaded.revision)throw Error('The saved run uses another model revision. Create a new scenario.');await navigator.locks.request('oncotics-browser-run',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another Oncotics tab is running. Pause it before continuing here.');busy=true;controller=new AbortController();buttons();try{await runJob(current,{store,envelope:snapshot,generate:model.generate,signal:controller.signal,onChange:()=>{if(tab==='simulation')render();}});status('Run completed on this device. Inspect the labeled report.');}catch(e){status(current.error||e.message,!controller.signal.aborted);}finally{busy=false;controller=undefined;await list();render();}});}
async function action(fn){try{await fn();}catch(e){status(errorMessage(e),true);}finally{buttons();}}
$('load-model').onclick=()=>action(async()=>{busy=true;loadingModel=true;controller=new AbortController();buttons();$('model-progress').hidden=false;status('Loading model files from this website. No AI provider is contacted.');try{const identity=await model.loadModel(p=>{$('model-progress').value=Math.round(100*p.progress);$('device-info').textContent=p.text||'Loading…';},controller.signal);$('device-info').textContent='Loaded '+identity.id+' · inference stays on this device.';status('Browser AI ready. Retrieve and review public evidence.');}finally{busy=false;loadingModel=false;controller=undefined;$('model-progress').hidden=true;render();}});
$('cancel-load').onclick=()=>controller?.abort();
$('unload-model').onclick=()=>action(async()=>{busy=true;buttons();try{await model.unload();$('device-info').textContent='Model unloaded from memory. Cached files may remain in browser storage.';status('AI unloaded. Evidence and saved runs remain available.');}finally{busy=false;buttons();}});
$('retrieve').onclick=()=>action(async()=>{if(!$('public-only').checked)throw Error('Confirm public, non-patient research use first.');busy=true;controller=new AbortController();buttons();snapshot=undefined;current=undefined;$('reviewed').checked=false;try{const result=await retrieve(concepts($('concepts').value),[...$('sources').querySelectorAll('input:checked')].map(x=>x.value),aliases,{signal:controller.signal,onProgress:(done,total)=>status('Retrieving public evidence: '+done+' / '+total+' requests completed.')});await store.freeze(result);snapshot=result;tab='evidence';render();status(result.snapshot.records.length?'Evidence saved locally. Inspect records and coverage, then return to Overview.':'No supported evidence retrieved. Inspect failures or import a public-provider response.');}finally{busy=false;controller=undefined;}});
$('scenario-form').onsubmit=event=>{event.preventDefault();if(busy)return;action(async()=>{const f=new FormData(event.target),spec=validateSpec({title:f.get('title'),question:f.get('question'),assumptions:String(f.get('assumptions')).split('\n').map(x=>x.trim()).filter(Boolean),rounds:Number(f.get('rounds')),agents:Number(f.get('agents')),research_only:$('public-only').checked,public_data_only:$('public-only').checked,reviewed:$('reviewed').checked});if(!snapshot)throw Error('Retrieve evidence first.');busy=true;buttons();try{current=await newJob(spec,snapshot,model.identity());await store.save(current);tab='simulation';render();await list();await execute();}finally{busy=false;buttons();}});};
$('import-evidence').onclick=()=>action(async()=>{if(!$('public-only').checked)throw Error('Confirm public, non-patient research use first.');const file=$('import-file').files[0];if(!file||file.size>4*1024*1024)throw Error('Choose a public-provider JSON file smaller than 4 MB.');const source=$('import-source').value,query=$('import-query').value;busy=true;buttons();try{const result=await importResponse(source,query,JSON.parse(await file.text()));await store.freeze(result);snapshot=result;current=undefined;$('reviewed').checked=false;tab='evidence';render();status('Imported source attribution remains ASSUMPTION. Review before running.');}finally{busy=false;buttons();}});
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;action(async()=>{if(b.dataset.tab){tab=b.dataset.tab;render();}if(b.dataset.scenario)await select(b.dataset.scenario);if(b.dataset.world){worldMode=b.dataset.world;render();}if(b.dataset.agent!==undefined){const a=current.agents[Number(b.dataset.agent)];$('agent-detail').innerHTML='<h2>'+esc(a.name)+'</h2>'+badge('SIMULATED')+json({profile:a,observed_statements:current.events.filter(e=>e.agent_id===a.id)})+'<p class="muted">Only the fixed role and saved statements are shown. Private reasoning and full model memory are not exposed.</p>';$('agent-dialog').showModal();}if(b.id==='pause-run'){controller?.abort();model.interrupt();status('Pausing; completed steps remain saved.');}if(b.id==='resume-run'&&!busy)await execute();if(b.id==='export-run')await exportRun();if(b.id==='export-report')download([current.report.title,'Research only',current.report.method,'Evidence SHA-256: '+current.report.evidence_sha256,...current.report.assumptions.map(a=>'ASSUMPTION: '+a.text),...current.report.statements.map(s=>'SIMULATED — '+s.agent_id+' / round '+s.round+'\n'+s.statement+'\nUncertainty: '+s.uncertainty+'\nModel-selected references: '+s.references.map(r=>r.ref).join(', ')),...current.report.limitations].join('\n\n'),'oncotics-report-'+current.id+'.txt','text/plain');});});
$('close-dialog').onclick=()=>$('agent-dialog').close();
$('new-scenario').onclick=()=>{snapshot=undefined;current=undefined;tab='overview';$('scenario-form').reset();render();status('Start with public evidence.');};
$('clear-data').onclick=()=>action(async()=>{if(!confirm('Delete all Scenario Lab evidence and scenarios saved in this browser? Export first. Imaging data and cached model files are not deleted.'))return;await store.clear();snapshot=undefined;current=undefined;tab='overview';await list();render();status('Local Scenario Lab records deleted.');});
$('scenario-form').addEventListener('input',event=>{if(event.target.id==='concepts'||event.target.closest('#sources')){snapshot=undefined;$('reviewed').checked=false;}buttons();});
window.addEventListener('beforeunload',event=>{if(busy){event.preventDefault();event.returnValue='';}});
await action(async()=>{store=await new LocalStore().open();aliases=await localJSON('/scenario-lab/entity-aliases.json');if(navigator.locks)await navigator.locks.request('oncotics-browser-run',{ifAvailable:true},async lock=>{if(lock)await store.recover();});await list();render();try{const manifest=await model.modelManifest();$('model-info').textContent='Included model: '+manifest.id+'. First loading transfers about '+Math.round(manifest.files.reduce((a,x)=>a+x.bytes,0)/1048576)+' MiB from this website. Inference runs on your GPU; Qwen2.5 3B is not medically validated and uses a non-commercial research license. Estimated GPU memory: '+Math.ceil(manifest.vram_required_MB/1024)+' GiB plus device/browser headroom.';await model.inspectDevice();$('device-info').textContent='WebGPU detected. Load the model when ready.';status('Browser workspace ready. Evidence retrieval and saved records are available.');}catch(e){$('device-info').textContent=e.message;status('Evidence workspace ready. '+e.message,true);}});
