import {escapeHTML as esc} from './core.mjs';
const badge=value=>'<span class="badge '+value+'">'+value+'</span>';
export function evidenceReview(job){return '<details><summary>Inspect the evidence excerpts selected for this scenario</summary><p class="muted">Exact provider-field excerpts, selected by local lexical ranking. Read the full source before interpreting an excerpt. Missing sections and qualifications may matter.</p>'+job.seed.map(p=>'<article class="record">'+badge(p.provenance)+' <strong>'+esc(p.ref)+' · '+esc(p.source_id)+'</strong><p>'+esc(p.text)+'</p><p class="muted">Field '+esc(p.locator)+' · characters '+p.start+'–'+p.end+' · receipt '+esc(p.receipt_id)+'</p><details><summary>Selection and integrity</summary><pre>'+esc(JSON.stringify({selection:p.selection,receipt_sha256:p.receipt_sha256,passage_sha256:p.passage_sha256,retrieved_at:p.retrieved_at},null,2))+'</pre></details></article>').join('')+'</details>';}
export function stateView(job){return '<p class="muted">'+badge('DERIVED')+' Research clock: '+job.environment.tick+' committed actions · '+job.environment.items.length+' unverified action targets. These counts describe the simulation; they do not measure scientific confidence.</p><details><summary>Inspect research rules and simulation state</summary><pre>'+esc(JSON.stringify({recipe:job.recipe,state:job.environment},null,2))+'</pre></details>';}
export function eventView(event){return '<article class="record">'+badge('SIMULATED')+'<strong>Step '+event.tick+' · '+esc(event.agent_id)+' · '+esc(event.action.replaceAll('_',' '))+'</strong><p>Target: '+esc(event.target)+'</p><p>'+esc(event.statement)+'</p><p class="muted">Needs verification: '+esc(event.uncertainty)+'</p><p class="muted">Model-selected references: '+esc(event.references.map(r=>r.ref).join(', ')||'none')+'</p><button type="button" data-event="'+esc(event.id)+'">Inspect context and rule transition</button></article>';}
export function networkView(job){
 if(!job||job.schema!=='oncotics-browser-scenario/2')return '<div class="empty">Select an enhanced scenario to inspect the event network. Original saved scenarios keep their original execution format.</div>';
 const coords=new Map(job.agents.map((a,i)=>[a.id,{x:100,y:70+i*120}]));for(const e of job.events)coords.set(e.id,{x:330+(e.round-1)*160,y:70+job.agents.findIndex(a=>a.id===e.agent_id)*120});
 const width=420+job.spec.rounds*160,height=120+job.agents.length*120;
 const edges=(job.simulation_graph?.edges||[]).map(edge=>{const a=coords.get(edge.from),b=coords.get(edge.to);if(!a||!b)return '';return '<path class="network-edge '+(edge.relation==='supplied_as_context'?'observation':'')+'" d="M'+a.x+','+a.y+' C'+(a.x+70)+','+a.y+' '+(b.x-70)+','+b.y+' '+b.x+','+b.y+'" marker-end="url(#network-arrow)"><title>'+esc(edge.relation.replaceAll('_',' '))+' · SIMULATED</title></path>';}).join('');
 const agents=job.agents.map(a=>{const p=coords.get(a.id);return '<g><circle class="agent-node" cx="'+p.x+'" cy="'+p.y+'" r="19"/><text x="'+p.x+'" y="'+(p.y+38)+'" text-anchor="middle">'+esc(a.id)+'</text></g>';}).join('');
 const events=job.events.map(e=>{const p=coords.get(e.id);return '<g class="event-node" tabindex="0" role="button" data-event="'+esc(e.id)+'" aria-label="Inspect step '+e.tick+' by '+esc(e.agent_id)+'"><circle cx="'+p.x+'" cy="'+p.y+'" r="20"/><text x="'+p.x+'" y="'+(p.y+5)+'" text-anchor="middle">'+e.tick+'</text><title>'+esc(e.action)+' · '+esc(e.target)+' · SIMULATED</title></g>';}).join('');
 return '<h2>Agent observations and timeline</h2><p class="muted">All nodes and links describe synthetic activity. Solid lines show who generated an event; dashed lines show earlier events actually supplied as context. No real social or causal relationship is inferred. Select a numbered event to inspect it.</p>'+stateView(job)+'<div class="network-wrap"><svg id="agent-network" viewBox="0 0 '+width+' '+height+'" role="group" aria-label="Interactive synthetic agent event network"><defs><marker id="network-arrow" viewBox="0 0 10 10" refX="25" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#7C3AED"/></marker></defs>'+edges+agents+events+'</svg></div><h3>Committed action timeline</h3>'+(job.events.length?'<ol class="event-timeline">'+job.events.map(e=>'<li>'+eventView(e)+'</li>').join('')+'</ol>':'<p class="empty">The network updates after each saved interaction.</p>');
}
export function eventInspection(job,id){const e=job.events.find(e=>e.id===id);if(!e)return '<p>Saved event not found.</p>';return '<h2>Step '+e.tick+' · '+esc(e.action.replaceAll('_',' '))+'</h2>'+eventView(e)+'<h3>Evidence supplied to this agent</h3>'+e.context_audit.supplied_refs.map(ref=>{const p=job.seed.find(x=>x.ref===ref);return '<article class="record">'+badge(p.provenance)+' '+esc(ref)+' · '+esc(p.locator)+'<p>'+esc(p.text)+'</p></article>';}).join('')+'<h3>Memory supplied to this agent</h3><p class="muted">Own events: '+esc(e.context_audit.own_event_ids.join(', ')||'none')+'<br>Other-agent observations: '+esc(e.context_audit.observed_event_ids.join(', ')||'none')+'</p><details><summary>Token usage, generation settings and hash chain</summary><pre>'+esc(JSON.stringify({generation:e.generation,diagnostics:e.diagnostics,context:e.context_audit,prior_state_sha256:e.prior_state_sha256,next_state_sha256:e.next_state_sha256,event_sha256:e.event_sha256},null,2))+'</pre></details>';}
export function agentMemory(job,agent){const memory=job.memories?.[agent.id];if(!memory)return '';const rows=ids=>ids.map(id=>{const e=job.events.find(e=>e.id===id);return '<p>'+badge('SIMULATED')+' Step '+e.tick+' · '+esc(e.agent_id)+': '+esc(e.statement)+'</p>';}).join('')||'<p class="muted">None yet.</p>';return '<h3>Own saved statements</h3>'+rows(memory.own_event_ids)+'<h3>Other-agent observations available under the public-rounds policy</h3>'+rows(memory.observed_event_ids)+'<p class="muted">Each turn selects a bounded subset; inspect the event network to see what was actually supplied. These observations are simulated beliefs, not additional source evidence.</p>';}
